import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

let goodsList = [{
        active: 0,
        index: 0,
        img: 'img/gbb.png',
        name: '乖巧宝宝主题桶含爆',
        price: 42,
        num: 0,
    },
    {
        active: 0,
        index: 1,
        img: 'img/gbb2.png',
        name: '乖巧宝宝TOP杯含可',
        price: 42,
        num: 0,
    },
    {
        active: 1,
        index: 2,
        img: 'img/baomihua1.png',
        name: '中份现制爆米花',
        price: 33,
        num: 0,
    },
    {
        active: 1,
        index: 3,
        img: 'img/baomihua2.png',
        name: '大份薯条番茄味',
        price: 39,
        num: 0,
    },
    {
        active: 1,
        index: 4,
        img: 'img/baomihua3.png',
        name: '中份薯条番茄味',
        price: 33,
        num: 0,
    },
    {
        active: 1,
        index: 5,
        img: 'img/baomihua4.png',
        name: '大份现制爆米花',
        price: 39,
        num: 0,
    },
    {
        active: 1,
        index: 6,
        img: 'img/baomihua5.png',
        name: '双拼爆薯番茄味',
        price: 39,
        num: 0,
    },
    {
        active: 2,
        index: 7,
        img: 'img/xyinliao1.png',
        name: '大杯现调芬达',
        price: 16,
        num: 0,
    },
    {
        active: 2,
        index: 8,
        img: 'img/xyinliao2.png',
        name: '中杯现调雪碧',
        price: 15,
        num: 0,
    },
    {
        active: 2,
        index: 9,
        img: 'img/xyinliao3.png',
        name: '雀巢热饮咖啡',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 10,
        img: 'img/xyinliao4.png',
        name: '热饮醇香牛乳奶茶',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 11,
        img: 'img/xyinliao2.png',
        name: '大杯现调雪碧',
        price: 16,
        num: 0,
    },
    {
        active: 2,
        index: 12,
        img: 'img/xyinliao6.png',
        name: '大悲西柚乳酸菌',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 13,
        img: 'img/xyinliao1.png',
        name: '中杯现调芬达',
        price: 15,
        num: 0,
    },
    {
        active: 2,
        index: 14,
        img: 'img/xyinliao8.png',
        name: '雀巢热饮甜牛奶',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 15,
        img: 'img/xyinliao9.png',
        name: '雀巢热饮果橙',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 16,
        img: 'img/xyinliao10.png',
        name: '大杯甘蔗百香果',
        price: 18,
        num: 0,
    },
    {
        active: 2,
        index: 17,
        img: 'img/xyinliao11.png',
        name: '大杯现调可乐',
        price: 16,
        num: 0,
    },
    {
        active: 2,
        index: 18,
        img: 'img/xyinliao11.png',
        name: '中杯现调可乐',
        price: 15,
        num: 0,
    },
    {
        active: 2,
        index: 19,
        img: 'img/xyinliao13.png',
        name: '大杯蜜桃乌龙茶',
        price: 18,
        num: 0,
    },
    {
        active: 3,
        index: 20,
        img: 'img/pyinliao1.png',
        name: '芬达橙味500ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 21,
        img: 'img/pyinliao2.png',
        name: '乳酸菌芒果汁',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 22,
        img: 'img/pyinliao3.png',
        name: '乳酸菌猕猴桃',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 23,
        img: 'img/pyinliao4.png',
        name: '美汁源果粒橙420ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 24,
        img: 'img/pyinliao5.png',
        name: '美汁源酷儿450ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 25,
        img: 'img/pyinliao6.png',
        name: '可口可乐500ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 26,
        img: 'img/pyinliao7.png',
        name: '巴黎水含气原味',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 27,
        img: 'img/pyinliao8.png',
        name: '可乐纤维500ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 28,
        img: 'img/pyinliao9.png',
        name: '零糖可乐500ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 29,
        img: 'img/pyinliao10.png',
        name: '维他可可椰子水',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 30,
        img: 'img/pyinliao11.png',
        name: '乳酸菌鲜橙汁',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 31,
        img: 'img/pyinliao12.png',
        name: '三得利黑乌龙茶',
        price: 18,
        num: 0,
    },
    {
        active: 3,
        index: 32,
        img: 'img/pyinliao13.png',
        name: '星冰乐摩卡',
        price: 32,
        num: 0,
    },
    {
        active: 3,
        index: 33,
        img: 'img/pyinliao14.png',
        name: '元气森林茉香乳茶',
        price: 22,
        num: 0,
    },
    {
        active: 3,
        index: 34,
        img: 'img/pyinliao15.png',
        name: 'AHHA汽水海盐柚子',
        price: 18,
        num: 0,
    },
    {
        active: 3,
        index: 35,
        img: 'img/pyinliao16.png',
        name: '元气森林原味乳茶',
        price: 22,
        num: 0,
    },
    {
        active: 3,
        index: 36,
        img: 'img/pyinliao17.png',
        name: 'NFC100%橙汁',
        price: 28,
        num: 0,
    },
    {
        active: 3,
        index: 37,
        img: 'img/pyinliao18.png',
        name: '雪碧纤维500ml',
        price: 15,
        num: 0,
    },
    {
        active: 3,
        index: 38,
        img: 'img/pyinliao19.png',
        name: 'AHHA汽水白桃乌龙',
        price: 15,
        num: 0,
    },
    {
        active: 4,
        index: 39,
        img: 'img/lingshi1.png',
        name: '炒年糕甜辣味',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 40,
        img: 'img/lingshi2.png',
        name: '莎布蕾火山小曲奇',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 41,
        img: 'img/lingshi3.png',
        name: '哈根达斯香草味',
        price: 48,
        num: 0,
    },
    {
        active: 4,
        index: 42,
        img: 'img/lingshi4.png',
        name: '现制德式烤肠*1',
        price: 12,
        num: 0,
    },
    {
        active: 4,
        index: 43,
        img: 'img/lingshi5.png',
        name: 'MIX脆脆条',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 44,
        img: 'img/lingshi6.png',
        name: '招牌韩式鸡米花小份',
        price: 18,
        num: 0,
    },
    {
        active: 4,
        index: 45,
        img: 'img/lingshi7.png',
        name: '乐飞利生巧流心冰淇淋',
        price: 24,
        num: 0,
    },
    {
        active: 4,
        index: 46,
        img: 'img/lingshi8.png',
        name: '香思粟小包',
        price: 12,
        num: 0,
    },
    {
        active: 4,
        index: 47,
        img: 'img/lingshi9.png',
        name: '海苔脆片原味',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 48,
        img: 'img/lingshi10.png',
        name: '炒年糕芝士味',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 49,
        img: 'img/lingshi11.png',
        name: 'U100海盐草莓味',
        price: 18,
        num: 0,
    },
    {
        active: 4,
        index: 50,
        img: 'img/lingshi12.png',
        name: 'Maito玉米片香辣',
        price: 26,
        num: 0,
    },
    {
        active: 4,
        index: 51,
        img: 'img/lingshi13.png',
        name: '现制德式烤肠*2',
        price: 24,
        num: 0,
    },
    {
        active: 4,
        index: 52,
        img: 'img/lingshi14.png',
        name: '光明大白兔冰淇淋',
        price: 12,
        num: 0,
    },
    {
        active: 4,
        index: 53,
        img: 'img/lingshi15.png',
        name: '亨思利锅巴海鲜微辣',
        price: 16,
        num: 0,
    },
    {
        active: 4,
        index: 54,
        img: 'img/lingshi16.png',
        name: 'Maito玉米片烧烤',
        price: 26,
        num: 0,
    },
    {
        active: 4,
        index: 55,
        img: 'img/lingshi17.png',
        name: '倍乐果棒棒糖',
        price: 12,
        num: 0,
    },
    {
        active: 4,
        index: 56,
        img: 'img/lingshi18.png',
        name: '趣莱福虾片蒜味',
        price: 26,
        num: 0,
    }
]

export default new Vuex.Store({
    state: {
        goodsList: []
    },
    mutations: {
        setGoods(state, val) {
            state.goodsList = val
        },
        goodsMinus(state, index) {
            let i = state.goodsList.findIndex(v => v.index == index);
            let item = state.goodsList[i];
            item.num--
                state.goodsList[i] = item
        },
        goodsPlus(state, index) {
            let i = state.goodsList.findIndex(v => v.index == index);
            let item = state.goodsList[i];
            item.num++
                state.goodsList[i] = item
        }
    },
    actions: {
        getGoodsList({ commit }) {
            setTimeout(v => {
                commit('setGoods', goodsList)
            }, 100)
        }
    },
    modules: {}
})